### ISSUE TITLE
Fix a minor typo

### ISSUE THREAD

**Issue by Thebys** [Bobris/bobril-build#23]
Hi, I noticed there are minor typos near the end of bb build log in messages: "Coping additional resources...", but it likely should be "Copying additional resources…"

Also "Build finished succesfully with…" should be "Build finished successfully with…"

Files affected seem to be:
…dist\additionalResources.js
…src\additionalResources.js
…dist\cliMain.js
…src\cliMain.js

Keep up the good work ^^

**Comment by kraklin** [comment]
Thank you.
We will fix it. Or if you want, you can create a pull request ;)
