### ISSUE TITLE
Installing present "missing" dependencies

### ISSUE THREAD

**Issue by horaklukas** [Bobris/bobril-build#37]
Newest version of bb (supporting yarn) install project dependencies every build, even if they are already installed...

![image](https://cloud.githubusercontent.com/assets/996088/21303943/4201c004-c5c2-11e6-96c7-55a27e970b4b.png)

**Comment by Bobris** [comment]
My output is like:

![image](https://cloud.githubusercontent.com/assets/284414/21309909/72da4e58-c5e0-11e6-9d38-503a8e3b0c50.png)

So I expect you don't have yarn installed?

**Comment by Bobris** [comment]
Ah I overlook you have "old" bobril-build version.

**Comment by horaklukas** [comment]
Ok, if newer version solve it I'm just going to upgrade.
