### ISSUE TITLE
StyleDef prefixing sometimes doesn't work

### ISSUE THREAD

**Issue by horaklukas** [Bobris/bobril-build#38]
Adding prefix for style names with `prefixStyleDefs` doesn't apply in some cases. Looks like it happens for styles returned from function. Example follows:

```
import * as b from 'bobril';

const notPrefixedComponentStyle = getStyle("blue", "green", "componentStyle");

function getStyle(color, hoverColor, hint) {
	return b.styleDef(
		{
			color: color
		}, {
			hover: {
				color: hoverColor
			}
		},
		hint
	);
}

const prefixedComponentStyle = b.styleDef(
	{
		backgroundColor: "red"
	}, {
		hover: {
			backgroundColor: "orange"
		}
	},
	"componentStyle2"
);

export let create = b.createComponent({
	render(ctx: b.IBobrilCtx, me: b.IBobrilNode) {
		me.children = "Sub component";

		b.style(
			me,
			notPrefixedComponentStyle,
			prefixedComponentStyle
		);
	}
});
```

As you can see on picture below, directly defined `prefixedComponentStyle` has `bb-` prefix defined in package.json while dynamiclly generated `notPrefixedComponentStyle` has not.

![image](https://cloud.githubusercontent.com/assets/996088/21305311/29ec6754-c5cb-11e6-8f3c-f41a82be07eb.png)

**Comment by Bobris** [comment]
True (it is not constant), I would not use hints in this case, but I will try to fix it too, just it will not be easy.
