### ISSUE TITLE
Error: Module moment in src/node_modules/bobril-g11n/src/msgFormatter not registered

### ISSUE THREAD

**Issue by Xrew** [Bobris/bobril-build#49]
Hi,
I have an issue with loader of nodejs modules. I have created a sandbox project to visualize the problem

The problem occurs, when I import typescript file, that is not in the hiearchy of the project directories **AND if I import bobril-g11n module**. If I do not import any file from ```otherProject``` than the project ```src``` works fine. 

The project structure:
![image](https://user-images.githubusercontent.com/1125082/34525291-acbe43f6-f09e-11e7-93ea-6a2ee90d3c82.png)
There are two projects. The one is located in ```src``` and the second in ```otherProject```. Each of this projects has own package.json.

**I want to use bobril-g11n module in project** ```src```.
![image](https://user-images.githubusercontent.com/1125082/34525352-ea04cc1c-f09e-11e7-8be4-80552126f3d6.png)

If I run bb command in src project, than bobril sources in the browser looks like:
![image](https://user-images.githubusercontent.com/1125082/34525387-0c397210-f09f-11e7-9647-c212c6fccf85.png)
Problem is in the module moment (internally used by bobril-g11n). The problem is, that the loader wants to load the module moment through the key: 
![image](https://user-images.githubusercontent.com/1125082/34525453-4cdf7da0-f09f-11e7-80ac-b8f689ea3377.png)
From the map:
![image](https://user-images.githubusercontent.com/1125082/34525467-58d537bc-f09f-11e7-97fa-3b877f83fe12.png)

It falls to the exception and in chrome console appears error:
```
loader.js:27 Uncaught Error: Module moment in src/node_modules/bobril-g11n/src/msgFormatter not registered
    at Function.R.r (loader.js:27)
    at loader.js:31
    at msgFormatter.ts:1
    at Function.R.r (loader.js:31)
    at loader.js:31
    at index.ts:2
    at Function.R.r (loader.js:31)
    at loader.js:31
    at index.ts:3
    at Function.R.r (loader.js:31)
```

Sandbox code to see the error:
[bobril-issue-sandbox.zip](https://github.com/Bobris/bobril-build/files/1600726/bobril-issue-sandbox.zip)

Am I doing something wrong? I tried to call g.initGlobalization, but it has no effect.

Any idea?

Thanks :)

**Comment by Bobris** [comment]
Maybe it could be problem on this line:
https://github.com/Bobris/bobril-build/blob/master/src/compilationCache.ts#L741
