### ISSUE TITLE
Cannot correctly bundle when using a library "html-to-text"

### ISSUE THREAD

**Issue by KungaEntertainment** [Bobris/bobril-build#51]
When bb b when using the html-to-text library, FE no longer loads.

```ts

import { htmlToText } from "html-to-text";

console.log(htmlToText("<p>Test</p>"));

```

![error](https://user-images.githubusercontent.com/65953109/151550451-33edb30c-6469-494a-aec9-da0b616a4bc0.jpg)

**Comment by Bobris** [comment]
Fixed (more like implemented) in 1.63.0
