### ISSUE TITLE
Q: How to execute specs for bobril components?

### ISSUE THREAD

**Issue by tomasdeml** [Bobris/bobril-build#7]
Does bobril-build currently support executing of TS tests/specs for bobril components? `bb` command does not output compiled TypeScript files to disk so it is not possible to create specs in TypeScript (AFAIK).

**Comment by Bobris** [comment]
Working on it last 2 days :-) Comming soon...

**Comment by Bobris** [comment]
One more day needed ... Really coming soon ...
